### ISSUE TITLE
Handle uncompletable tasks

### ISSUE THREAD

**Issue by mason3k** [jamiebrynes7/obsidian-todoist-plugin#216]
Uncompletable tasks are tasks that cannot be completed. See https://todoist.com/help/articles/how-to-create-an-uncompletable-task. They appear in the Todoist interface without a checkbox. 

The plugin should not produce a checkmark for these tasks

**Comment by jamiebrynes7** [comment]
Agreed this is suboptimal, however the checkbox is disabled so the task cannot be completed.

If your theme supports it or if you are familiar with CSS, this can be rendered differently:

```css
input[type="checkbox"].task-list-item-checkbox:disabled {
	display: none;
}
```

for example will hide the checkbox.
