### ISSUE TITLE
Whats up with the gigantic indentation?

### ISSUE THREAD

**Issue by acrylicus** [jamiebrynes7/obsidian-todoist-plugin#344]
<img width="400" alt="image" src="https://github.com/user-attachments/assets/ab5521a3-813d-4f0d-bef4-d957e8798598">

**Comment by hxii** [comment]
You can fix this with a CSS snippet:
```CSS
/* Todoist Plugin */
/* -- Padding and Margin Fixes */
ul.todoist-task-list {
  padding-inline-start: 0;
}

ul.todoist-task-list > li.task-list-item {
  margin-inline-start: 0
}
```
