### ISSUE TITLE
can I remove the project icon/name from a subtask with CSS ?

### ISSUE THREAD

**Issue by rui-nar** [jamiebrynes7/obsidian-todoist-plugin#76]
i can't seem to be able to identify a CSS class for subtasks in order to remove the icon/name of the project of the subtask since it's already visible/available on the main task ...

how can I achieve this ?

**Comment by jamiebrynes7** [comment]
Hey @rui-nar the following CSS snippet should do the job: 

```css
.task-list-item .task-list-item .task-project {
  display: none;
}
```

This will target the project section of any subtask.
